FROM node:lts-alpine

# install simple http server for static content
RUN npm install -g http-server

# make 'app' folder working directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install dependencies
RUN npm install

# copy project files/folders to current working directory
COPY . .

# build app
RUN npm run build

EXPOSE 8080
CMD ["http-server", "dist"]